name: 💥 Nuclei - Vulnerability Scan

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev # Required for Naabu

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up Tools Bugbounty
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        shell: bash

      - name: 💥 Nuclei - Vulnerability Scan
        run: |
          TARGET=`cat input/domains.txt`
          nuclei -t all-templates -l "domain/$TARGET/active_urls.txt" -include-tags fuzz -o "domain/$TARGET/nuclei_output.txt"
          git add "domain/$TARGET/nuclei_output.txt"
        shell: bash

      - name: 👨🏻‍💻 Commit results to Github
        run: |
          git config --local user.email "YOUR_EMAIL_GITHUB"
          git config --global user.name "USERNAME"
          git commit -m "PD-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
